from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import START,END,StateGraph
from typing_extensions import TypedDict
from pprint import pprint

load_dotenv()

# State 
class GraphState(TypedDict):
    # Original user requirement
    user_query: str
    # Analysis prepared by the first node
    analysis: str
    # Prompt created by the second node
    generated_prompt: str
    # Final response generated by AI
    response: str
    
# LLM
llm = ChatGoogleGenerativeAI(
    model = "gemini-flash-latest"
)

# # Node
# def chatBot(state: GraphState):
#     result = llm.invoke(state['user_query'])
#     return {
#         "response" : result.content
#     }

#Requirement analyser node
def requirement_analyzer(state: GraphState):
    print("Requirement Analyser executing....")
    analysis = f"""
    Requirement: {state['user_query']}
    Goal: Understand what user wants.
"""
    return{
        "analysis": analysis
    } 


#Prompt generator node
def prompt_generator(state: GraphState):
    print("Prompt Generator executing....")
    prompt = f"""
    You are an expert software engineer.
    Based on this analysis:
    {state['analysis']}
    Generate a detailed solution.
"""
    return {
        "generated_prompt":prompt
    }

# Ai assistance
def ai_assistant(state: GraphState):
    print("AI Assistant executing....")
    result = llm.invoke(state['generated_prompt'])
    return {
        "response" : result.content
    }

# Build Graph
builder = StateGraph(GraphState)
# builder.add_node("chatbot", chatBot)
# builder.add_edge(START, "chatbot")
# builder.add_edge("chatbot", END)

builder.add_node("requirement_analyzer", requirement_analyzer)
builder.add_node("prompt_generator", prompt_generator)
builder.add_node("ai_assistant", ai_assistant)

builder.add_edge(START, "requirement_analyzer")
builder.add_edge("requirement_analyzer", "prompt_generator")
builder.add_edge("prompt_generator", "ai_assistant")
builder.add_edge("ai_assistant", END)
graph = builder.compile()

#Execute
result = graph.invoke(
    {
        "user_query": "Create a Login api using spring boot"
    }
)
pprint(result["response"][0]["text"])
# print(result["response"])