"""
Shared Memory
Acts as a common storage for all agents
Responsibilites:
1. Stores information generated by agents
2. Retrieve information for sownstream agents
3. Provide a common communication mechanism
4. Remain independent of any specific AI Agent
"""
from typing import Any
class SharedMemory:
    """
    Share memory accessible by every agent
    """

    def __init__(self):
        self.memory: dict[str,Any] = {}

    def add(self, key: str, value: Any) -> None:
        """
        Store data
        """

        self.memory[key] = value

    def get(self,key: str) -> str:
        """
        retrieve memory
        """
        return self.memory.get(key)
    
    def exist(self, key: str)-> bool:
        """
        Chcek if the key exists
        """
        return key in self.memory
    
    def remove(self, key: str) -> None:
        """
        Remove a key from memory
        Args:
            key: Memory key
        """
        self._memory.pop(key,None)

    def clear(self) -> None:
        """
        Clear memory
        """

        self.memory.clear()

    def get_all(self) -> dict[str, Any]:
        """
        Return the complete memory
        Returns:
            Dictionary containing all stored values
        """
        return self._memory
        
    def display(self) -> None:
        """
        Print current memory
        """

        print("="*50)
        print("SHARED MEMORY")
        print("="*50)
        for key, value in self.memory.items():
            print(f"{key}")
            print(value)
            print("="*50) 